/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyResultRouteImport } from './routes/verify-result'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as PredictMotionRouteImport } from './routes/predict-motion'
import { Route as PredictRouteImport } from './routes/predict'
import { Route as HelperRouteImport } from './routes/helper'
import { Route as GlobalPathwaysRouteImport } from './routes/global-pathways'
import { Route as CounsellingRouteImport } from './routes/counselling'
import { Route as ConnectivityRouteImport } from './routes/connectivity'
import { Route as ClubsHackathonsRouteImport } from './routes/clubs-hackathons'
import { Route as AlternatePathwayRouteImport } from './routes/alternate-pathway'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CounsellingCompareRouteImport } from './routes/counselling.compare'
import { Route as CounsellingCollegeRouteImport } from './routes/counselling.college'
import { Route as CounsellingCareerRouteImport } from './routes/counselling.career'
import { Route as CounsellingSessionIdRouteImport } from './routes/counselling.session.$id'

const VerifyResultRoute = VerifyResultRouteImport.update({
  id: '/verify-result',
  path: '/verify-result',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictMotionRoute = PredictMotionRouteImport.update({
  id: '/predict-motion',
  path: '/predict-motion',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictRoute = PredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const HelperRoute = HelperRouteImport.update({
  id: '/helper',
  path: '/helper',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalPathwaysRoute = GlobalPathwaysRouteImport.update({
  id: '/global-pathways',
  path: '/global-pathways',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellingRoute = CounsellingRouteImport.update({
  id: '/counselling',
  path: '/counselling',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectivityRoute = ConnectivityRouteImport.update({
  id: '/connectivity',
  path: '/connectivity',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsHackathonsRoute = ClubsHackathonsRouteImport.update({
  id: '/clubs-hackathons',
  path: '/clubs-hackathons',
  getParentRoute: () => rootRouteImport,
} as any)
const AlternatePathwayRoute = AlternatePathwayRouteImport.update({
  id: '/alternate-pathway',
  path: '/alternate-pathway',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellingCompareRoute = CounsellingCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => CounsellingRoute,
} as any)
const CounsellingCollegeRoute = CounsellingCollegeRouteImport.update({
  id: '/college',
  path: '/college',
  getParentRoute: () => CounsellingRoute,
} as any)
const CounsellingCareerRoute = CounsellingCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => CounsellingRoute,
} as any)
const CounsellingSessionIdRoute = CounsellingSessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => CounsellingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alternate-pathway': typeof AlternatePathwayRoute
  '/clubs-hackathons': typeof ClubsHackathonsRoute
  '/connectivity': typeof ConnectivityRoute
  '/counselling': typeof CounsellingRouteWithChildren
  '/global-pathways': typeof GlobalPathwaysRoute
  '/helper': typeof HelperRoute
  '/predict': typeof PredictRoute
  '/predict-motion': typeof PredictMotionRoute
  '/processing': typeof ProcessingRoute
  '/verify-result': typeof VerifyResultRoute
  '/counselling/career': typeof CounsellingCareerRoute
  '/counselling/college': typeof CounsellingCollegeRoute
  '/counselling/compare': typeof CounsellingCompareRoute
  '/counselling/session/$id': typeof CounsellingSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alternate-pathway': typeof AlternatePathwayRoute
  '/clubs-hackathons': typeof ClubsHackathonsRoute
  '/connectivity': typeof ConnectivityRoute
  '/counselling': typeof CounsellingRouteWithChildren
  '/global-pathways': typeof GlobalPathwaysRoute
  '/helper': typeof HelperRoute
  '/predict': typeof PredictRoute
  '/predict-motion': typeof PredictMotionRoute
  '/processing': typeof ProcessingRoute
  '/verify-result': typeof VerifyResultRoute
  '/counselling/career': typeof CounsellingCareerRoute
  '/counselling/college': typeof CounsellingCollegeRoute
  '/counselling/compare': typeof CounsellingCompareRoute
  '/counselling/session/$id': typeof CounsellingSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alternate-pathway': typeof AlternatePathwayRoute
  '/clubs-hackathons': typeof ClubsHackathonsRoute
  '/connectivity': typeof ConnectivityRoute
  '/counselling': typeof CounsellingRouteWithChildren
  '/global-pathways': typeof GlobalPathwaysRoute
  '/helper': typeof HelperRoute
  '/predict': typeof PredictRoute
  '/predict-motion': typeof PredictMotionRoute
  '/processing': typeof ProcessingRoute
  '/verify-result': typeof VerifyResultRoute
  '/counselling/career': typeof CounsellingCareerRoute
  '/counselling/college': typeof CounsellingCollegeRoute
  '/counselling/compare': typeof CounsellingCompareRoute
  '/counselling/session/$id': typeof CounsellingSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alternate-pathway'
    | '/clubs-hackathons'
    | '/connectivity'
    | '/counselling'
    | '/global-pathways'
    | '/helper'
    | '/predict'
    | '/predict-motion'
    | '/processing'
    | '/verify-result'
    | '/counselling/career'
    | '/counselling/college'
    | '/counselling/compare'
    | '/counselling/session/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alternate-pathway'
    | '/clubs-hackathons'
    | '/connectivity'
    | '/counselling'
    | '/global-pathways'
    | '/helper'
    | '/predict'
    | '/predict-motion'
    | '/processing'
    | '/verify-result'
    | '/counselling/career'
    | '/counselling/college'
    | '/counselling/compare'
    | '/counselling/session/$id'
  id:
    | '__root__'
    | '/'
    | '/alternate-pathway'
    | '/clubs-hackathons'
    | '/connectivity'
    | '/counselling'
    | '/global-pathways'
    | '/helper'
    | '/predict'
    | '/predict-motion'
    | '/processing'
    | '/verify-result'
    | '/counselling/career'
    | '/counselling/college'
    | '/counselling/compare'
    | '/counselling/session/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlternatePathwayRoute: typeof AlternatePathwayRoute
  ClubsHackathonsRoute: typeof ClubsHackathonsRoute
  ConnectivityRoute: typeof ConnectivityRoute
  CounsellingRoute: typeof CounsellingRouteWithChildren
  GlobalPathwaysRoute: typeof GlobalPathwaysRoute
  HelperRoute: typeof HelperRoute
  PredictRoute: typeof PredictRoute
  PredictMotionRoute: typeof PredictMotionRoute
  ProcessingRoute: typeof ProcessingRoute
  VerifyResultRoute: typeof VerifyResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-result': {
      id: '/verify-result'
      path: '/verify-result'
      fullPath: '/verify-result'
      preLoaderRoute: typeof VerifyResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predict-motion': {
      id: '/predict-motion'
      path: '/predict-motion'
      fullPath: '/predict-motion'
      preLoaderRoute: typeof PredictMotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predict': {
      id: '/predict'
      path: '/predict'
      fullPath: '/predict'
      preLoaderRoute: typeof PredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helper': {
      id: '/helper'
      path: '/helper'
      fullPath: '/helper'
      preLoaderRoute: typeof HelperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-pathways': {
      id: '/global-pathways'
      path: '/global-pathways'
      fullPath: '/global-pathways'
      preLoaderRoute: typeof GlobalPathwaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counselling': {
      id: '/counselling'
      path: '/counselling'
      fullPath: '/counselling'
      preLoaderRoute: typeof CounsellingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectivity': {
      id: '/connectivity'
      path: '/connectivity'
      fullPath: '/connectivity'
      preLoaderRoute: typeof ConnectivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs-hackathons': {
      id: '/clubs-hackathons'
      path: '/clubs-hackathons'
      fullPath: '/clubs-hackathons'
      preLoaderRoute: typeof ClubsHackathonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alternate-pathway': {
      id: '/alternate-pathway'
      path: '/alternate-pathway'
      fullPath: '/alternate-pathway'
      preLoaderRoute: typeof AlternatePathwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counselling/compare': {
      id: '/counselling/compare'
      path: '/compare'
      fullPath: '/counselling/compare'
      preLoaderRoute: typeof CounsellingCompareRouteImport
      parentRoute: typeof CounsellingRoute
    }
    '/counselling/college': {
      id: '/counselling/college'
      path: '/college'
      fullPath: '/counselling/college'
      preLoaderRoute: typeof CounsellingCollegeRouteImport
      parentRoute: typeof CounsellingRoute
    }
    '/counselling/career': {
      id: '/counselling/career'
      path: '/career'
      fullPath: '/counselling/career'
      preLoaderRoute: typeof CounsellingCareerRouteImport
      parentRoute: typeof CounsellingRoute
    }
    '/counselling/session/$id': {
      id: '/counselling/session/$id'
      path: '/session/$id'
      fullPath: '/counselling/session/$id'
      preLoaderRoute: typeof CounsellingSessionIdRouteImport
      parentRoute: typeof CounsellingRoute
    }
  }
}

interface CounsellingRouteChildren {
  CounsellingCareerRoute: typeof CounsellingCareerRoute
  CounsellingCollegeRoute: typeof CounsellingCollegeRoute
  CounsellingCompareRoute: typeof CounsellingCompareRoute
  CounsellingSessionIdRoute: typeof CounsellingSessionIdRoute
}

const CounsellingRouteChildren: CounsellingRouteChildren = {
  CounsellingCareerRoute: CounsellingCareerRoute,
  CounsellingCollegeRoute: CounsellingCollegeRoute,
  CounsellingCompareRoute: CounsellingCompareRoute,
  CounsellingSessionIdRoute: CounsellingSessionIdRoute,
}

const CounsellingRouteWithChildren = CounsellingRoute._addFileChildren(
  CounsellingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlternatePathwayRoute: AlternatePathwayRoute,
  ClubsHackathonsRoute: ClubsHackathonsRoute,
  ConnectivityRoute: ConnectivityRoute,
  CounsellingRoute: CounsellingRouteWithChildren,
  GlobalPathwaysRoute: GlobalPathwaysRoute,
  HelperRoute: HelperRoute,
  PredictRoute: PredictRoute,
  PredictMotionRoute: PredictMotionRoute,
  ProcessingRoute: ProcessingRoute,
  VerifyResultRoute: VerifyResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
